### ISSUE TITLE
enable/disable confirmation in bsd integration

### ISSUE THREAD

**Issue by lolownia** [WeMoveEU/bsd_api#10]
For thos who will do confirmation in speakout or those who don't want it: disable confirmation in bsd_api

**Comment by scardinius** [comment]
@tttp @lolownia  Could you explain what exactly do you mean?

**Comment by lolownia** [comment]
This is already implemented in BSD_API opt-in OFF/ON settings. Thanks!

**Comment by scardinius** [comment]
ok, thanks for closing issue. Could you review rest of your issues?
