### ISSUE TITLE
Sync automatically campaigns between speakout and civi

### ISSUE THREAD

**Issue by tttp** [WeMoveEU/bsd_api#11]
So the rule for the campaigns:

- each campaign in speakout matches a campaign (you need civicampaign enabled) in civi.
- the external id of the civi campaign is the (internal) id in speakout
- if a campaign belongs to another campaign (eg it's the translation of), use the parent id of the camaign to link the "sub" campaign to the master campaign

For wemove, we have two extra fields:
-  the language of the campaign (eg en_GB) 
- the id of the message id to send for the opt-in message

The aim is to automatically creates the campaign in civi based on what we have in civi. I'm not sure what's the best way of doing that: fetching the campaign.json every hour or so to check if there is something new?

Ideally, it will also be synced to the CMS, eg to automatically populate the list of campaigns on the main site.

**Comment by scardinius** [comment]
@tttp I prepared method for creating new campaign on CiviCRM. It is in test mode ;-)

I need additional keys from response on [external_id].json:
* msg_template_id
* preferred_language
* parent_id

**Comment by tttp** [comment]
So speakout won't have these fields, at least for a while.

What we have is an internal name, that contains "_EN" or "_FR"... that we can use to get the language

But right now the campaigners will have to manually choose the message_id, language and parent_id.

**Comment by scardinius** [comment]
What exactly do you mean "manually choose"? Where, on which step?

**Comment by tttp** [comment]
Create it with english and no parent and they will have to go in the UI
later to set up to something they want (the manual part). but it's outside
of the extension, it's not on your plate ;)

And voila ;)

**Comment by scardinius** [comment]
ok, I prepared method with default values
