### ISSUE TITLE
check for duplicate

### ISSUE THREAD

**Issue by tttp** [WeMoveEU/bsd_api#2]
If a contact exists already, use it instead of creating a new one

rule: same first name, same last name, same email
don't update the source, update the address if different?

should we start handling the engagement, eg adding a tag "active" because he/she signed twice?

**Comment by tttp** [comment]
@scardinius you are creating duplicate addresses if you find the same contact for now.

It needs more testing, but IMO better if
1) you don't create duplicate addresses, if one exists already
2) don't create duplicate groups if one exists already

**Comment by scardinius** [comment]
Fixed duplicate addresses.

* If address already exists, postal code is updated
* During updating postal code location type doesn't change to Home

**Comment by scardinius** [comment]
Fixed duplicate groups.

* If contact doesn't have a group -> add group on status Pending
* If contact already has group on status "Added" -> don't touch this relation
* If contact already has group on status "Removed" -> add group on status Pending
