### ISSUE TITLE
record sharing 

### ISSUE THREAD

**Issue by tttp** [WeMoveEU/bsd_api#3]
as new activity or simply as a flag "share on TW" or "share on FB", or as custom field on the sign activity?

right now, easier to create a new activity type "share" and create and activity, we'll see how we use that data later

**Comment by scardinius** [comment]
Done.

activity type: `share`, status: `Completed`

**Comment by scardinius** [comment]
* Added external campaign id to activity record
* Fixed bug to setting campaign id
