### ISSUE TITLE
new campaign has no type and start date

### ISSUE THREAD

**Issue by scardinius** [WeMoveEU/bsd_api#38]
During creating new campaign if it doesn't exist in CiviCRM there aren't type and start date.

Type -> Petition
Start date -> Now

**Comment by tttp** [comment]
I'm not sure where the problem comes from, but the default email is invalid
too (html encoded, so "Xavier" &lt;info@wemove.eu&gt;)

Can you set it so it looks clean?
X+

**Comment by scardinius** [comment]
Done, type and start date is setting up
