### ISSUE TITLE
duplicated contacts

### ISSUE THREAD

**Issue by scardinius** [WeMoveEU/bsd_api#39]
@tttp :

speakeasy is creating duplicates where they shouldn't be that many, for instance, is seems that we have identical (first, last, email) with different sources (one sign, the other share)

Would it be possible that every share creates a duplicate? share should never create any new contact

the other source of duplicate MIGHT be that we have several contacts with the same (first, last, email), so existing duplicates, and when you have a new petition, it fails to find one (because they are >1) and create a new contact

In that case, you should just take the oldest (ie lower contact_id) instead of creating yet another duplicate

**Comment by scardinius** [comment]
On speakout forms we use first name, last name and email. During creating new contact I first check if such combination exists in database. Problem occurs when in database already exists contact with only email or email+first name.

My proposals
* In all cases we have to identify contact ONLY BY EMAIL.
* If new submission has a additional information such as last name, this field is updating but only if is empty in database (not replace)
* If in database are more than 1 contact with the same email, we use the oldest one as a primary

Therefore It's necessary to merge existing contacts by page `Find and Merge Duplicate Contacts` on our CiviCRM

**Comment by tttp** [comment]
Dedupe is really tricky, you can make two errors: see the same person as
being two different records, or try to put two different person into the
same record.

Like probability, the more you avoid one type of error, the more you
increase the other one.

so one trick might be to "progressively match", so contact.get (email=
example.org, return=first,last,email), and then choose the one that has the
more similar fields basically, how the dedupe rules work)

I'm checking how they do it with other CRMs, might be overthinking, email
match only could be the answer

X+

**Comment by scardinius** [comment]
I agree for progressively matching - looking for the best similar contact (email, first and last).

Other cases are a job for our campaigners and they have to decide what to do. It could be several combination which it's not necessary to implement in code.

**Comment by scardinius** [comment]
Done.
