### ISSUE TITLE
remove the hardcoded parts

### ISSUE THREAD

**Issue by tttp** [WeMoveEU/bsd_api#4]
They are several things that are hardcoded
- the campaign id
- the language/message to send

It should be possible, based on the external id (the campaign id in speakout) to find the civicrm campaign_id and the related message templates to be sent.

as step one, put that into the civicrm.settings.php or a config into the extension?

**Comment by scardinius** [comment]
How to retrieve campaing id based on external_id:
```SQL
SELECT id FROM civicrm_campaign WHERE external_identifier = %1;
```

**Comment by tttp** [comment]
hopefully, using the api instead...

**Comment by scardinius** [comment]
@tttp  you're right. It will be better.

**Comment by tttp** [comment]
So I have created the custom fields for language and template id that you can fetch from the campaign

    $result = civicrm_api3('Campaign', 'get', array(
      'sequential' => 1,
      'return' => "name,title,parent_id,custom_3,custom_4",
    ));

https://www.wemove.eu/civicrm/campaign?reset=1&subPage=campaign

can you use the template for the mail sending and the language for the language (as we know from the campaign language what the member language is)

**Comment by scardinius** [comment]
Done :-)

* language from custom field is used to preferred language in case of new user
* template id from custom field is used to confirmation email

**Comment by tttp** [comment]
Much better indeed. Let's take it one step further and store the settings outside of the code completely.

@scardinius can you check on the wiki?
http://wiki.civicrm.org/confluence/display/CRMDOC/Settings+Reference (the bit about extension)

Step 1 if to move it out of the .php code and put it into a big array:
https://github.com/eileenmcnaughton/org.civicrm.multisite/blob/master/settings/Multisite.setting.php
Step 2 is to fetch that from the setting instead of internal attributes in our class
Step 3 is to add a UI (freaking minimal, eg don't bother getting a drop down with the groups, just the id)
https://github.com/eileenmcnaughton/nz.co.fuzion.civixero/blob/master/CRM/Civixero/Form/XeroSettings.php

A setting to add that would make marcin super happy is a "opt-in"  boolean
if yes, it's like now
if no, 
- add the contact to the group with status "Added"
- add the activity with the status "Confirmed"
- skip the send email step

Ping me to clarify if you want

**Comment by scardinius** [comment]
Done :)
