### ISSUE TITLE
add a "with" relationship with the activity

### ISSUE THREAD

**Issue by tttp** [WeMoveEU/bsd_api#5]
So in theory, you can create an activity with only the source_contact being set, and it _almost_ works fine

That's what this extension does

However, the activity search ignores all activities that don't have a with, so it's hard to search

Can you quickly chat on civicrm channel to see if that's something that can be easily fixed in the core (and check the code, but it's a not so easy part if I recall)

If not, we need to add it

**Comment by scardinius** [comment]
There are two possibilities:

1. On "Edit Search Criteria" on page "Find activities" you can change default selection from "With" to "Added by". After that all activities are selected.
2. If you want to add "with" or "assigned" relation to activity you can use such code:
```php
$params = array(
  'sequential' => 1,
  'id' => $activity_id,
  'assignee_contact_id' => $assigned_contact_id,
  'target_contact_id' => $with_contact_id,
);
$result = civicrm_api3('Activity', 'create', $params);
``` 

So, what are we doing?

**Comment by tttp** [comment]
hey cool,

This is enough for now, just train the users to choose the right "added" and voila, done ;)
