### ISSUE TITLE
Something wrong with the campaign_id

### ISSUE THREAD

**Issue by scardinius** [WeMoveEU/bsd_api#6]
@tttp reported: Something wrong with the campaign_id: it's not set

This problem occurs when external id is a child campaign, for example different language.

Each campaign on Speakout has own corresponding campaign on CiviCRM but only one of them is a main (parent).

What to do: 

* get parent_id; 
* if parent_id is null, get id

**Comment by tttp** [comment]
always use id, the parent_id is going to be used for the analysis

X+

**Comment by scardinius** [comment]
In this case current solution is already good.
It's important to remember set up `civicrm_campaign.external_identifier` with external id.

```SQL
SELECT
  id, name, parent_id, external_identifier
FROM civicrm_campaign
WHERE external_identifier IS NOT NULL;
```

I've already set up external identifier to current campaigns.
