### ISSUE TITLE
Changing the status of activity (scheduled->completed)

### ISSUE THREAD

**Issue by scardinius** [WeMoveEU/bsd_api#7]
New user -> activity status: Scheduled
After confirm -> change status to Completed

Old user -> activity status: Completed
no confirmation email

**Comment by tttp** [comment]
for now, still send the confirmation email (it contains more stuff beside the confirmation text)

**Comment by scardinius** [comment]
This status is set up only on first step - after filled out the petition form. On the step after click on confirmation link there is information only about contact id and hash (in url). Therefore the method `CRM_Bsd_Page_Confirm->run()` doesn't have any information about activity id. I can't change status of activity without id of activity.

My proposal: Add activity_id to parameters of method `CRM_Bsd_Page_BSD->sendConfirm()`.

Then I can include activity's ID into email. What do you think?

**Comment by tttp** [comment]
yeap, includes the activity id in the link is the right solution
