### ISSUE TITLE
Prepare SQL query for Dataviz indicator

### ISSUE THREAD

**Issue by scardinius** [WeMoveEU/bsd_api#8]
@tttp requirements:
* so with that I can do a first dataviz about the signatories and be able to filter by status or if contact_created=activity_created (ie new contact)
* so I'd need a select name, contact created date, activity date, activity status from activity join contact
* get who signed, when, if they confirmed, and if they are new in the db or old
* being able to see if our petition talks only to our existing members or being able to attract new ones is super important

**Comment by tttp** [comment]
clarfication: always fetch all the data with their status, the filtering is done on the result, client side

**Comment by scardinius** [comment]
First approach to query:

* indicator1: NEW user only if YmdHi is the same
* indicator2: NEW during 10 minutes from creating contact
* activity type: Petition or share
* `ORDER BY` and `LIMIT` just for review

```sql
SELECT
  ac.contact_id,
  ac.activity_id,
  a.activity_type_id,
  a.campaign_id,
  c.display_name,
  atv.name AS activity_type_name,
  a.status_id,
  CASE
  WHEN a.status_id = 1
    THEN 'Scheduled'
  WHEN a.status_id = 2
    THEN 'Completed'
  END AS status_name,
  c.created_date AS contact_create_date,
  a.activity_date_time,
  CASE
    WHEN DATE_FORMAT(c.created_date, '%Y%m%d%H%i') = DATE_FORMAT(a.activity_date_time, '%Y%m%d%H%i')
    THEN 'NEW'
    ELSE 'OLD'
  END AS indicator1,
  CASE
  WHEN DATE_FORMAT(a.activity_date_time, '%Y%m%d%H%i') - DATE_FORMAT(c.created_date, '%Y%m%d%H%i') < 10
    THEN 'NEW'
  ELSE 'OLD'
  END AS indicator2
FROM civicrm_contact c
  JOIN civicrm_activity_contact ac ON c.id = ac.contact_id
  JOIN civicrm_activity a ON a.id = ac.activity_id
  JOIN civicrm_option_value atv ON atv.option_group_id = 2 AND atv.value = a.activity_type_id
WHERE a.is_deleted = 0 AND a.activity_type_id IN (32, 54)
ORDER BY a.activity_date_time DESC
LIMIT 1000;
```

**Comment by tttp** [comment]
nice start,

imo, no need to make it too smart, just return 1 and 2 as the status id,
same thing for the new vs old, just return the two dates and let the
consumer sort it out

i didn't think about it, but makes sense to get all the activities,
provides a nice overview of what's going on right now

i'll play a bit with it see if we can get a sexy dataviz

**Comment by scardinius** [comment]
@tttp I added column with names just for convenience review. 

The same approach there is in indicators values. If you want, You can change them into 1 and 2 values. As you wish.

If you want to see all activities, just remove `AND a.activity_type_id IN (32, 54)` line :-)
