### ISSUE TITLE
Set the contact creation date to be the same as the activity date

### ISSUE THREAD

**Issue by tttp** [WeMoveEU/bsd_api#9]
So we wanted to say if contact creation date==activity date, it's a new contact, otherwise and exiting one.

It's not working, as the contact create date is set to now() but activity date is taken from speakout (so a few sec or min away)

@scardinius can you set with the api explorer if it's possible to set the created_date of the contact via the api?

If it's the case, can you fix to set the created_date in the api, and write a one off sql to run by hand to update the create date so it's the activity date for all the contact where source like "speakout petition%"

if we can't set the create date, ping me, we'll see how to work around that

**Comment by scardinius** [comment]
Proper date is setting up now due to PR #15 

Next step is updating previous users.

**Comment by tttp** [comment]
the next step moves to #16
